#!/bin/bash
set -e

# Add user from environment variables
useradd -m -s /bin/bash $USERNAME
echo "$USERNAME:$PASSWORD" | chpasswd &> /dev/null
ln -s my-work/.profile /home/$USERNAME/.profile

# Start ttyd
exec ttyd -W -p 8787 login
